mysql =  {'host': '127.0.0.1',
          'user': 'root',
          'password' : 'root',
          'database' : 'pathofinder_db',
          'hostadress' : "localhost"} #"'%'"}

db_tables_views = { #dictionary containing all tables and table-views and their attributes
    'oligo' : ['oligo_ID', 'oligo_name', 'oligo_type',
                   'sequence', 'description', 'entry_date',
                   'creator', 'update_date', 'modifier',
                   'label5prime', 'label3prime', 'labelM1',
                   'labelM1position', 'pathogen_name', 'target', 'notes'], 
    'project_oligo' : ['oligo_ID', '`project_oligo`.project_ID'], 
    'project' : ['project_ID', 'project_name'], 
    'batch' : ['batch_number', 'oligo_ID', 'synthesis_level_ordered',
                   'purification_method', 'synthesis_level_delivered',
                   'spec_sheet_location', 'order_number', 'delivery_date',
                   'order_status'],
    'order' : ['order_number', 'supplier_ID', 'order_date', 'employee_ID'],
    'supplier' : ['supplier_ID', 'supplier_name'],
    'oligo_oder_list' : ['.oligo_orderlist_PK', 'batch_number', 'supplier_ID',
                             'oligo_ID', 'employee_ID'],
    'employee' : ['employee_ID', 'emp_name', 'password'],
    'lab_report' : ['lab_report_PK', 'lab_report_location'],
    'experiment' : ['experiment_ID', 'lab_report_PK', 'experiment_date'],
    'approval' : ['experiment_ID', 'test_number', 'oligo_ID_1',
                      'oligo_ID_2', 'oligo_ID_3', 'oligo_ID_4', 'oligo_ID_5', 'approved_status'],
    'order_bin' : ['bin_ID', 'oligo_name', 'oligo_type',
                   'sequence', 'description', 'entry_date',
                   'creator', 'label5prime', 'label3prime', 'labelM1',
                   'labelM1position', 'pathogen_name', 'target', 'notes',
                   'synthesis_level_ordered', 'purification_method',
                   'order_status', 'project_ID', 'project_name',
                   'supplier_ID', 'supplier_name'],
    'order_queue' : ['queue_ID', 'oligo_name', 'oligo_type',
                   'sequence', 'description', 'entry_date',
                   'creator', 'label5prime', 'label3prime', 'labelM1',
                   'labelM1position', 'pathogen_name', 'target', 'notes',
                   'synthesis_level_ordered', 'purification_method',
                   'order_status', 'project_ID', 'project_name',
                   'supplier_ID', 'supplier_name'],
    'batches_order_supplier' : ['batch_number', 'oligo_ID', 'synthesis_level_ordered',
                   'purification_method', 'synthesis_level_delivered',
                   'spec_sheet_location', 'order_number', 'delivery_date',
                   'order_status', 'order_date', 'orderer', 'supplier_name'],
    "oligo_recent_batch" : ['oligo_ID', 'oligo_name', 'recent_batch', 'order_status',
                         'oligo_type', 'sequence', 'description', 'entry_date',
                         'creator', 'update_date', 'modifier', 'label5prime',
                         'label3prime', 'labelM1', 'labelM1position',
                         'pathogen_name', 'target', 'notes'],
    'suppliers_analysis': ['supplier_name', 'Delivery_Difference', 'Synthesis_Difference'],
    'oligos_from_project': ['oligo_ID', 'oligo_name', 'oligo_type', 'sequence', 'description',
            'entry_date', 'creator', 'update_date', 'modifier', 'label5prime',
            'label3prime', 'labelM1', 'labelM1position', 'notes'],
    'everything' : ['oligo_ID', 'oligo_name', 'oligo_type',
                   'sequence', 'description', 'entry_date',
                   'creator', 'update_date', 'modifier',
                   'label5prime', 'label3prime', 'labelM1',
                   'labelM1position', 'pathogen_name', 'target',
                    'notes', 'batch_number', 'synthesis_level_ordered',
                   'purification_method', 'synthesis_level_delivered',
                   'spec_sheet_location', 'order_number', 'delivery_date',
                   'order_status', 'supplier_ID', 'order_date', 'orderer',
                    'supplier_name', 'project_ID', 'project_name']
                    }                                            
