mysql =  {'host': '127.0.0.1',
          'user': 'root',
          'password' : 'root',
          'database' : 'pathofinder_db'}

db_tables_views = { #dictionary containing all tables and table-views and their attributes
    'oligo' : ['oligo_ID', 'oligo_name', 'oligo_type',
                   'sequence', 'description', 'entry_date',
                   'creator', 'update_date', 'modifier',
                   'label5prime', 'label3prime', 'labelM1',
                   'labelM1position', 'pathogen_name', 'target', 'notes'], 
    'project_oligo' : ['oligo_ID', '`project_oligo`.project_ID'], 
    'project' : ['project_ID', 'project_name'], 
    'batch' : ['batch_number', 'oligo_ID', 'synthesis_level_ordered',
                   'purification_method', 'synthesis_level_delivered',
                   'spec_sheet_location', 'order_number', 'delivery_date',
                   'order_status'],
    'order' : ['order_number', 'supplier_ID', 'order_date', 'employee_ID'],
    'supplier' : ['supplier_ID', 'supplier_name'],
    'oligo_oder_list' : ['.oligo_orderlist_PK', 'batch_number', 'supplier_ID',
                             'oligo_ID', 'employee_ID'],
    'employee' : ['employee_ID', 'emp_name'],
    'lab_report' : ['lab_report_PK', 'lab_report_location'],
    'experiment' : ['experiment_ID', 'lab_report_PK', 'experiment_date'],
    'approval' : ['experiment_ID', 'test_number', 'oligo_ID_fwd',
                      'oligo_ID_rev', 'oligo_ID_probe', 'oligo_ID_4', 'oligo_ID_5', 'approved_status'],
    'oligo_bin' : ['oligo_ID', 'oligo_name', 'oligo_type',
                   'sequence', 'description', 'entry_date',
                   'creator', 'update_date', 'modifier',
                   'label5prime', 'label3prime', 'labelM1',
                   'labelM1position', 'pathogen_name', 'target', 'notes'],
    'batches_supplier' : ['batch_number', 'oligo_ID', 'synthesis_level_ordered',
                   'purification_method', 'synthesis_level_delivered',
                   'spec_sheet_location', 'order_number', 'delivery_date',
                   'order_status', 'order_date', 'employee', 'supplier_name'],
    "oligo_batch" : ['oligo_ID', 'oligo_name', 'recent_batch', 'order_status',
                         'oligo_type', 'sequence', 'description', 'entry_date',
                         'creator', 'update_date', 'modifier', 'label5prime',
                         'label3prime', 'labelM1', 'labelM1position',
                         'pathogen_name', 'target', 'notes'],
    'approval_lab_report' : ['experiment_ID', 'test_number', 'oligo_ID_fwd',
                             'oligo_ID_rev', 'oligo_ID_4', 'oligo_ID_5',
                             'approved_status', 'experiment_date', 'lab_report_location'],
    'oligolist_test_results' : ['oligo_ID', 'oligo_name', 'Approved', 'Neutral',
                                'Disapproved', 'Percentage_of_approval'],
    'supplier_synthesis_quality': ['supplier_name', 'Synthesis_Difference'],
    'approved_oligos_for_project' : ['project_name', 'experiment_date', 'experiment_ID',
            'oligo_ID_fwd', 'oligo_ID_rev', 'oligo_ID_probe',
            'oligo_ID_4', 'oligo_ID_5'],
    'oligos_from_project': ['oligo_ID', 'oligo_name', 'oligo_type', 'sequence', 'description',
            'entry_date', 'creator', 'update_date', 'modifier', 'label5prime',
            'label3prime', 'labelM1', 'labelM1position', 'notes']
                    }                                            
